# Generated by Django 4.1.5 on 2023-01-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_movie_user_alter_movie_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(upload_to='covers'),
        ),
    ]
